###############

GPU: [0,1]

VERBOSE: True

MODEL:
  MODE: 'Enhancement'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 2
  NUM_EPOCHS: 200
  LR_INITIAL: 5e-4

TRAINING:
  TRAIN_PS: 256
  VAL_PS: 256
  RESUME: True

  TRAIN_DIR_KCL: 'KCL/training'           # path to training data
  TRAIN_DIR_RLE: 'RLE/training'
  VAL_DIR_KCL: 'KCL/val'              # path to validation data
  VAL_DIR_RLE: 'RLE/val'
  SAVE_DIR: './checkpoints_IGLFM/'    # path to save models and images
  SAVE_IMAGES: True
  # VAL_AFTER_EVERY: 1
