###############

GPU: [1]

VERBOSE: True

MODEL:
  MODE: 'Enhancement'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 24
  NUM_EPOCHS: 120
  LR_INITIAL: 1e-3

TRAINING:
  TRAIN_PS: 256
  VAL_PS: 256
  RESUME: False

  TRAIN_DIR_KCL: 'KCL/training'           # path to training data
  TRAIN_DIR_RLE: 'RLE/training'
  VAL_DIR_KCL: 'KCL/val'              # path to validation data
  VAL_DIR_RLE: 'RLE/val'
  SAVE_DIR: './checkpoints_BLGM'    # path to save models and images
  SAVE_IMAGES: True
  # VAL_AFTER_EVERY: 1
